# Generated by Django 3.2.2 on 2021-12-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_distribuidor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidadVendido',
            field=models.IntegerField(default=0),
        ),
    ]
